USE [DB]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE <tableName>(
	[field1] [int] IDENTITY(1,1) NOT NULL,
	[field2] [varchar](64) NOT NULL,
	[field3] [varchar](32) NULL,L,
	[field4] [int] NULL,
	[field5] [varchar](255) NULL,
 CONSTRAINT [PK_tableName] PRIMARY KEY CLUSTERED 
(
	[Ifield1] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO



